### PR TITLE
Enable nightly DynamoDB backups for CloudFormed tables

### PR DESCRIPTION
**Pull request by jacobwinch**
## What does this change?

This PR allows us to start backing up the `price-migration-engine-cohort-spec` DynamoDB table using https://github.com/guardian/aws-backup. For more details on this project see [this doc](https://docs.google.com/document/d/11EZtuVHCnjavE9AYLroiuDUsMzbp2ulFBtj4VkyCKNc/edit) and this [audit](https://docs.google.com/spreadsheets/d/1gNh_yQ3GVo_dVAemgZfRZM_MaQxep6_x-hzrhvVBGHY/edit#gid=1523470588) that @guardian/devx-reliability have been working on with Heads of Engineering.

## How to test

I should be able to test this by deploying to `CODE`.

I will double check that backups are taken as expected after merging (this should happen the night after this PR is merged).

## How can we measure success?

We will be able to recover (most) data stored in this table in the unlikely event that it is deleted.

## Have we considered potential risks?

Yes, a number of risks related to performance, cost and privacy were considered. See [this doc](https://docs.google.com/document/d/11EZtuVHCnjavE9AYLroiuDUsMzbp2ulFBtj4VkyCKNc/edit#heading=h.vwt7syo8ng40) for more details.

## Question for maintainers of this project

I think the [Riff-Raff project is defined here](https://github.com/guardian/price-migration-engine/blob/03f06fda46c77f63b7f0fb64c55c15fad644f2ce/build.sbt#L36), but it [hasn't been deployed to `CODE` for a long time](https://riffraff.gutools.co.uk/deployment/history?projectName=Retention%3A%3APriceMigrationEngine%3A%3ADynamoDb&stage=CODE&pageSize=20&page=1) and has [never been deployed to `PROD`](https://riffraff.gutools.co.uk/deployment/history?projectName=Retention%3A%3APriceMigrationEngine%3A%3ADynamoDb&stage=PROD&pageSize=20&page=1).

Is deploying via Riff-Raff the correct way to test / release these infrastructure changes?

### CODE REVIEW

**Review by shtukas — APPROVED** [review]

**Comment by jacobwinch** [comment]
Have moved this back into draft status as @shtukas and I would like to double check how these tables are being used (if at all) before merging this in!

**Comment by kelvin-chappell** [comment]
`PriceMigrationEngineDynamoTable` held the original 2020 cohort before the individual cohort tables were created programmatically.  All the data in it should be in the data lake now so the table and its cloudform config can probably be deleted but @shtukas can confirm.
The `CohortSpecTable` is still in use.  If it's going to be backed up nightly, should be able to do without the [PITR](https://github.com/guardian/price-migration-engine/blob/7106750d83fe870ad458e1c94ac997ec54f202e9/dynamoDb/cfn/cfn.yaml#L29-L30).

**Comment by shtukas** [comment]
Thanks Kelvin, yes, I was about to double check and issue a cleaning PR. More to come soon :)

**Comment by shtukas** [comment]
Cleaning PR: https://github.com/guardian/price-migration-engine/pull/956

**Review by shtukas — APPROVED** [review]

**Comment by jacobwinch** [comment]
> I will double check that backups are taken as expected after merging (this should happen the night after this PR is merged).

This is working in `PROD`:

image

**Pull request merged**
